# Generated by Django 2.1.3 on 2018-11-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('freelancer_id', models.AutoField(db_column='Freelancer_Id', primary_key=True, serialize=False)),
                ('freelancer_ful_name', models.CharField(db_column='Freelancer_Ful_Name', max_length=150)),
                ('freelancer_email', models.CharField(db_column='Freelancer_Email', max_length=100)),
                ('freelancer_password', models.CharField(db_column='Freelancer_Password', max_length=45)),
                ('freelancer_recv_updt', models.IntegerField(db_column='Freelancer_Recv_Updt')),
                ('freelancer_contact_no', models.CharField(db_column='Freelancer_Contact_No', max_length=45)),
                ('freelancer_location', models.CharField(db_column='Freelancer_Location', max_length=100)),
                ('freelancercol', models.CharField(blank=True, db_column='Freelancercol', max_length=45, null=True)),
                ('freelancer_skills', models.CharField(blank=True, db_column='Freelancer_Skills', max_length=200, null=True)),
                ('freelancer_qualifications', models.CharField(blank=True, db_column='Freelancer_Qualifications', max_length=200, null=True)),
            ],
            options={
                'db_table': 'freelancer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobOwner',
            fields=[
                ('jo_id', models.AutoField(db_column='JO_Id', primary_key=True, serialize=False)),
                ('jo_full_name', models.CharField(db_column='JO_Full_Name', max_length=150)),
                ('jo_email', models.CharField(db_column='JO_Email', max_length=100)),
                ('jo_password', models.CharField(db_column='JO_Password', max_length=45)),
                ('jo_salon_name', models.CharField(blank=True, db_column='JO_Salon_Name', max_length=45, null=True)),
                ('jo_recv_updt', models.IntegerField(db_column='JO_Recv_Updt')),
                ('jo_contact_no_off', models.CharField(blank=True, db_column='JO_Contact_No_Off', max_length=45, null=True)),
                ('jo_contact_no_personnel', models.CharField(db_column='JO_Contact_No_Personnel', max_length=45)),
                ('jo_location', models.CharField(db_column='JO_Location', max_length=100)),
            ],
            options={
                'db_table': 'job_owner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(db_column='Payment_Id', primary_key=True, serialize=False)),
                ('payement_amount', models.DecimalField(db_column='Payement_Amount', decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(db_column='Payment_Status', max_length=6)),
                ('payment_init_date', models.DateField(db_column='Payment_Init_Date')),
                ('payment_due_date', models.DateField(blank=True, db_column='Payment_Due_Date', null=True)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_date', models.DateField(db_column='Schedule_Date', primary_key=True, serialize=False)),
                ('schedule_time', models.CharField(db_column='Schedule_Time', max_length=45)),
                ('schedule_desc', models.CharField(blank=True, db_column='Schedule_Desc', max_length=45, null=True)),
            ],
            options={
                'db_table': 'schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(db_column='Task_Id', primary_key=True, serialize=False)),
                ('task_date', models.DateField(db_column='Task_Date')),
                ('task_time', models.CharField(blank=True, db_column='Task_Time', max_length=45, null=True)),
                ('task_status', models.CharField(blank=True, db_column='Task_Status', max_length=4, null=True)),
                ('taskcol', models.CharField(blank=True, db_column='Taskcol', max_length=45, null=True)),
                ('task_rating', models.CharField(blank=True, db_column='Task_Rating', max_length=1, null=True)),
                ('task_review', models.CharField(blank=True, db_column='Task_Review', max_length=500, null=True)),
            ],
            options={
                'db_table': 'task',
                'managed': False,
            },
        ),
    ]
